# vim:ft=kitty

## name: Modus Vivendi
## author: Protesilaos Stavrou
## license: GNU GPLv3
## blurb: Highly accessible themes made for GNU Emacs, conforming with the highest
## standard for colour contrast between background and foreground values (WCAG AAA)

# The basic colors
foreground              #ffffff
background              #000000
selection_foreground    #ffffff
selection_background    #1c3b59

# Cursor colors
cursor                  #ffffff
cursor_text_color       #000000

# kitty window border colors
active_border_color     #c6daff
inactive_border_color   #646464

# Tab bar colors
active_tab_foreground   #ffffff
active_tab_background   #545454
inactive_tab_foreground #969696
inactive_tab_background #2f2f2f

# The basic 16 colors
# black
color0 #000000
color8 #434852

# red
color1 #ef596f
color9 #ef596f

# green
color2  #00c06f
color10 #00c06f

# yellow
color3  #e5c07b
color11 #e2be7d

# blue
color4  #2fafff
color12 #79a8ff

# magenta
color5  #feacd0
color13 #b6a0ff

# cyan
color6  #2bbac5
color14 #00d3d0

# white
color7  #a6a6a6
color15 #ffffff
