return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	dependencies = {
		{ "mason-org/mason.nvim", opts = {} },
	},
	cond = not vim.g.vscode,
	opts = {
		ensure_installed = {
			"bash-language-server",
			"checkmake",
			"clang-format",
			"clangd",
			"css-lsp",
			"eslint_d",
			"fixjson",
			"gdscript-formatter",
			"html-lsp",
			"ltex-ls-plus",
			"lua-language-server",
			"prettierd",
			"pyright",
			"ruff",
			"rust-analyzer",
			"stylua",
			"tombi",
			"typescript-language-server",
			"typos-lsp",
		},
		auto_update = true,
	},
}
