return {
	"olimorris/onedarkpro.nvim",
	priority = 1000, -- Ensure it loads first
	cond = not vim.g.vscode,
	init = function()
		require("onedarkpro").setup({
			colors = {
				-- bg = "#000000",
				fg = "#ffffff",
				red = "#ef596f",
				orange = "#d19a66",
				yellow = "#e5c07b",
				green = "#00c06f",
				cyan = "#2bbac5",
				blue = "#2fafff",
				purple = "#b6a0ff",
				white = "#abb2bf",
				black = "#000000",
				gray = "#434852",
				highlight = "#e2be7d",
				comment = "#989898",
				none = "NONE",
				blue_warmer = "#79a8ff",
				pink = "#feacd0",
				cursorline = "require('onedarkpro.helpers').lighten('bg', 10, 'onedark_dark')",
				light_float_bg = "require('onedarkpro.helpers').lighten('bg', 15, 'onedark_dark')",
				float_bg = "require('onedarkpro.helpers').lighten('bg', 0, 'onedark_dark')",
				bg_select = "#1C3B59",
				bg_statusline = "require('onedarkpro.helpers').lighten('bg', 25, 'onedark_dark')",
			},
			highlights = {
				-- 	Function = { fg = "${pink}" },
				Visual = { bg = "${bg_select}" },
				String = { fg = "${blue_warmer}" },
				-- 	Identifier = { fg = "${cyan}" },
				CursorLine = { bg = "${cursorline}" },
				LspReferenceText = { bg = "${bg_select}" },
				RenderMarkdownCode = { link = "NormalFloat" },
				TelescopeNormal = { bg = "${float_bg}" },
				TelescopeBorder = { bg = "${float_bg}" },
				TelescopeSelection = { fg = "NONE", bg = "${bg_select}" },
				TelescopeMatching = { fg = "${yellow}" },
				Question = { fg = "${red}" },

				BlinkCmpLabelMatch = { fg = "${yellow}" },
				Pmenu = { bg = "${light_float_bg}" },
				PmenuSel = { bg = "${bg_select}" },
				PmenuThumb = { bg = "${comment}" },
				PmenuSbar = { bg = "${cursorline}" },

				-- 	["@constant"] = { fg = "${red}" },
				-- 	["@function"] = { fg = "${pink}" },
				-- 	["@operator"] = { fg = "${red}" },
				["@string"] = { fg = "${blue_warmer}" },
				-- 	["@property"] = { fg = "${blue}" },
				-- 	["@variable"] = { fg = "${blue}" },
				-- 	["@variable.member"] = { link = "@variable" },
				-- 	["@variable.parameter"] = { link = "@variable" },
			},
			styles = {
				comments = "italic",
			},
		})
		vim.cmd("colorscheme onedark_dark")
	end,
}
