add_newline = false
continuation_prompt = "[](bright-black) "
format = """$fill $cmd_duration$jobs$nix_shell$directory"""
# format = """$fill \
#       $status\
#       $username\
#       $hostname\
#       $localip\
#       $shlvl\
#       $singularity\
#       $kubernetes\
#       $vcsh\
#       $fossil_branch\
#       $fossil_metrics\
#       $git_branch\
#       $git_commit\
#       $git_state\
#       $git_metrics\
#       $git_status\
#       $hg_branch\
#       $pijul_channel\
#       $docker_context\
#       $package\
#       $c\
#       $cmake\
#       $cobol\
#       $cpp\
#       $daml\
#       $dart\
#       $deno\
#       $dotnet\
#       $elixir\
#       $elm\
#       $erlang\
#       $fennel\
#       $gleam\
#       $golang\
#       $guix_shell\
#       $haskell\
#       $haxe\
#       $helm\
#       $java\
#       $julia\
#       $kotlin\
#       $gradle\
#       $lua\
#       $nim\
#       $nodejs\
#       $ocaml\
#       $opa\
#       $perl\
#       $php\
#       $pulumi\
#       $purescript\
#       $python\
#       $quarto\
#       $raku\
#       $rlang\
#       $red\
#       $ruby\
#       $rust\
#       $scala\
#       $solidity\
#       $swift\
#       $terraform\
#       $typst\
#       $vlang\
#       $vagrant\
#       $zig\
#       $buf\
#       $nix_shell\
#       $conda\
#       $meson\
#       $spack\
#       $memory_usage\
#       $aws\
#       $gcloud\
#       $openstack\
#       $azure\
#       $nats\
#       $direnv\
#       $env_var\
#       $mise\
#       $crystal\
#       $custom\
#       $sudo\
#       $cmd_duration\
#       $jobs\
#       $battery\
#       $time\
#       $os\
#       $container\
#       $netns\
#       $shell\
#       $directory\
#       $line_break\
#       $character\
#     """

[character] 
format = "$symbol "
success_symbol = "[](cyan)"
error_symbol = "[](red)"
vimcmd_symbol = "[](cyan)"
vimcmd_replace_symbol = "[<](yellow)"
vimcmd_replace_one_symbol = "[<](yellow)"
vimcmd_visual_symbol = "[<](magenta)"

[fill] 
symbol = "─"
style = "white"

[aws] 
format = "[$symbol($profile)(($region))( $duration)]($style) "
symbol = " "

[buf]
symbol = " "

[bun]
format = "[$symbol($version)]($style) "

[c] 
format = "[$symbol($version(-$name))]($style) "
symbol = " "

[cmake]
format = "[$symbol($version)]($style) "
symbol = " "

[cmd_duration]
format = "[ $duration]($style) "

[cobol]
format = "[$symbol($version)]($style) "

[conda]
format = "[$symbol$environment]($style) "
symbol = " "

#[cpp]
# format = "[$symbol($version(-$name))]($style) "

[crystal]
format = "[$symbol($version)]($style)"
symbol = " "

[daml]
format = "[$symbol($version)]($style) "

[dart]
format = "[$symbol($version)]($style)"
symbol = " "

[deno]
format = "[$symbol($version)]($style) "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "green"
fish_style_pwd_dir_length = 1
read_only = " 󰌾"

[docker_context]
format = "[$symbol$context]($style) "
symbol = " "

[dotnet]
format = "[$symbol($version)(🎯 $tfm)]($style) "

[elixir]
format = "[$symbol($version (OTP $otp_version))]($style) "
symbol = " "

[elm]
format = "[$symbol($version)]($style) "
symbol = " "

[erlang]
format = "[$symbol($version)]($style) "

[fennel]
format = "[$symbol($version)]($style) "
symbol = " "

[fossil_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[gcloud]
format = "[$symbol$account(@$domain)(($region))]($style) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "cyan"

[git_commit]
tag_symbol = "  "
style = "cyan"

[git_metrics]
format = "([$added]($added_style)/[$deleted]($deleted_style)) "
added_style = "green"
deleted_style = "red"
disabled = true

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "cyan"
conflicted = "[ ](red)"
ahead = "[󰶼](yellow)"
behind = "[󰶹](yellow)"
diverged = "[󰹹](red)"
up_to_date = ""
untracked = "[ ](green)"
stashed = "[ ](blue)"
modified = "[ ](yellow)"
staged = "[󰦘 ](blue)"
renamed = "[ ](yellow)"
deleted = "[ ](red)"
typechanged = ""

[golang]
format = "[$symbol($version)]($style) "
symbol = " "

[gradle]
format = "[$symbol($version)]($style) "
symbol = " "

[guix_shell]
format = "[$symbol]($style) "
symbol = " "

[haskell]
format = "[$symbol($version)]($style) "
symbol = " "

[haxe]
format = "[$symbol($version)]($style) "
symbol = " "

[hg_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[hostname]
ssh_symbol = " "

[java]
format = "[$symbol($version)]($style) "
symbol = " "

[jobs]
symbol = "󱌣 "

[julia]
format = "[$symbol($version)]($style) "
symbol = " "

[kotlin]
format = "[$symbol($version)]($style) "
symbol = " "

[kubernetes]
format = "[$symbol$context( ($namespace))]($style) "

[lua]
format = "[$symbol($version)]($style) "
symbol = " "

[memory_usage]
format = "$symbol[$ram( | $swap)]($style) "
symbol = "󰍛 "

[meson]
format = "[$symbol$project]($style) "
symbol = "󰔷 "

[nim]
format = "[$symbol($version)]($style) "
symbol = "󰆥 "

[nix_shell]
format = "[$symbol$state( ($name))]($style) "
symbol = " "

[nodejs]
format = "[$symbol($version)]($style) "
symbol = " "

[ocaml]
format = "[$symbol($version)(($switch_indicator$switch_name))]($style) "
symbol = " "

[opa]
format = "[$symbol($version)]($style) "

[openstack]
format = "[$symbol$cloud(($project))]($style) "

[os]
format = "[$symbol]($style) "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
format = "[$symbol$version]($style) "
symbol = "󰏗 "

[perl]
format = "[$symbol($version)]($style) "
symbol = " "

[php]
format = "[$symbol($version)]($style) "
symbol = " "

[pijul_channel]
format = "[$symbol$channel]($style) "
symbol = " "

#[pixi]
#format = "[$symbol$version( $environment)]($style) "

[pulumi]
format = "[$symbol$stack]($style) "

[purescript]
format = "[$symbol($version)]($style) "

[python]
format = "[$symbol$pyenv_prefix $version $virtualenv]($style) "
symbol = " "

[raku]
format = "[$symbol($version-$vm_version)]($style) "

[red]
format = "[$symbol($version)]($style) "

[rlang]
symbol = "󰟔 "

[ruby]
format = "[$symbol($version)]($style) "
symbol = " "

[rust]
format = "[$symbol($version)]($style) "
symbol = "󱘗 "

[scala]
format = "[$symbol($version)]($style) "
symbol = " "

[solidity]
format = "[$symbol($version)]($style) "

[spack]
format = "[$symbol$environment]($style) "

[status]
format = "[$symbol$status]($style) "
symbol = " "
disabled = false

[sudo]
format = "[as $symbol]($style) "

[swift]
format = "[$symbol($version)]($style) "
symbol = " "

[terraform]
format = "[$symbol$workspace]($style) "

[time]
format = "[$time]($style) "

[username]
format = "[$user]($style) "

[vagrant]
format = "[$symbol($version)]($style) "

[vlang]
format = "[$symbol($version)]($style) "

[zig]
format = "[$symbol($version)]($style) "
symbol = " "
